/*****************************************************************************/
/* Triangle MicroWorks, Inc.                         Copyright (c) 1997-2020 */
/*****************************************************************************/
/*                                                                           */
/* This file is the property of:                                             */
/*                                                                           */
/*                       Triangle MicroWorks, Inc.                           */
/*                      Raleigh, North Carolina USA                          */
/*                       www.TriangleMicroWorks.com                          */
/*                          (919) 870-6615                                   */
/*                                                                           */
/* This Source Code and the associated Documentation contain proprietary     */
/* information of Triangle MicroWorks, Inc. and may not be copied or         */
/* distributed in any form without the written permission of Triangle        */
/* MicroWorks, Inc.  Copies of the source code may be made only for backup   */
/* purposes.                                                                 */
/*                                                                           */
/* Your License agreement may limit the installation of this source code to  */
/* specific products.  Before installing this source code on a new           */
/* application, check your license agreement to ensure it allows use on the  */
/* product in question.  Contact Triangle MicroWorks for information about   */
/* extending the number of products that may use this source code library or */
/* obtaining the newest revision.                                            */
/*                                                                           */
/*****************************************************************************/

/* file: dnpbncfg.h
 * description: This file is intended for internal SCL use only.
 *   Private DNP session support
 */
#ifndef DNPBNCFG_DEFINED
#define DNPBNCFG_DEFINED


#include "tmwscl/utils/tmwtarg.h"


/*field size definition for the field at the start of each section containing the size of the section */
#define DNPBNCFG_SECTION_SIZE_FIELD_SIZE      4

/*field size definitions for section 1.1 of the binary configuration file */
#define DNPBNCFG_CONTROL_SIZE1_1              4
#define DNPBNCFG_DEVFUNCTION_SIZE1_1          4
#define DNPBNCFG_VENDORNAME_SIZE1_1           32
#define DNPBNCFG_DEVICENAME_SIZE1_1           32
#define DNPBNCFG_HARDWAREVERSION_SIZE1_1      16
#define DNPBNCFG_SOFTWAREVERSION_SIZE1_1      16
#define DNPBNCFG_DOCVERSIONNUM_SIZE1_1        4
#define DNPBNCFG_DNPLEVELSSUPPORTED_SIZE1_1   4
#define DNPBNCFG_SUPPORTEDFUNCTIONBLOCK_SIZE1_1     4
#define DNPBNCFG_METHODSTOSETCONFIGPARAMS_SIZE1_1   4
#define DNPBNCFG_CONNECTIONSSUPPORTED_SIZE1_1       4

/*field size definitions for section 1.2 of the binary configuration file */
#define DNPBNCFG_CONTROL_SIZE1_2              4
#define DNPBNCFG_SPECIALCONTROL_SIZE1_2       4
#define DNPBNCFG_PORTNAME_SIZE1_2             16
#define DNPBNCFG_BAUDRATE_SIZE1_2             4
#define DNPBNCFG_FLOWCONTROL_SIZE1_2          4
#define DNPBNCFG_LINKSTATUSINTERVAL_SIZE1_2   4
#define DNPBNCFG_MINBACKOFFTIMEFORCOLLISIONAVIODANCE_SIZE1_2          4
#define DNPBNCFG_MAXRANDOMBACKOFFTIMEFORCOLLISIONAVIODANCE_SIZE1_2    4
#define DNPBNCFG_RECEIVERINTERCHARTIMEOUT_SIZE1_2   4
#define DNPBNCFG_INTERCHARMAXGAPSINTX_SIZE1_2       4

/*field size definitions for section 1.3 of the binary configuration file */
#define DNPBNCFG_CONTROL_SIZE1_3              4
#define DNPBNCFG_SPECIALCONTROL_SIZE1_3       4
#define DNPBNCFG_PORTNAME_SIZE1_3             16
#define DNPBNCFG_TYPEOFENDPOINT_SIZE1_3       4
#define DNPBNCFG_IPOFDEVICE_SIZE1_3           64
#define DNPBNCFG_SUBNETMASK_SIZE1_3           64
#define DNPBNCFG_GATEWAYIPADDR_SIZE1_3        64
#define DNPBNCFG_ACCEPTSTCPCONNSORUDPDARAGRAMS_SIZE1_3        4
#define DNPBNCFG_IPADDRSTOACCEPTTCPANDUDPCOUNT_SIZE1_3        4
#define DNPBNCFG_IPADDRTOACCEPTTCPANDUDP_SIZE1_3              64
#define DNPBNCFG_TCPLISTENPORTNUMBER_SIZE1_3                  4
#define DNPBNCFG_TCPLISTENPORTNUMBEROFREMOTE_SIZE1_3          4
#define DNPBNCFG_TCPKEEPALIVETIMER_SIZE1_3                    4
#define DNPBNCFG_LOCALUDPPORT_SIZE1_3                         4
#define DNPBNCFG_DESTUDPPORTFORDNP3REQ_SIZE1_3                4
#define DNPBNCFG_DESTUDPPORTFORINITIALUNSOLNULLRESP_SIZE1_3   4
#define DNPBNCFG_DESTUDPPORTFORRESPONSES_SIZE1_3              4
#define DNPBNCFG_MULTIPLEMASTERCONNECTIONS_SIZE1_3            4
#define DNPBNCFG_TIMESYNCHSUPPORT_SIZE1_3                     4
#define DNPBNCFG_MAXNUMIPADDRS1_3              8

/*field size definitions for section 1.4 of the binary configuration file */
#define DNPBNCFG_CONTROL_SIZE1_4                        4
#define DNPBNCFG_SPECIALCONTROL_SIZE1_4                 4
#define DNPBNCFG_DATALINKADDRESS_SIZE1_4                4
#define DNPBNCFG_DNP3SOURCEADDRVALIDATION_SIZE1_4       4
#define DNPBNCFG_DNP3SOURCEADDRS_SIZE1_4                4
#define DNPBNCFG_SENDSCONFIRMEDUSERDATAFRAMES_SIZE1_4   4
#define DNPBNCFG_DATALINKLAYERCONFIRMTIMEOUT_SIZE1_4    4
#define DNPBNCFG_MAXDATALINKRETRIES_SIZE1_4             4
#define DNPBNCFG_MAXNUMOCTETSTXINDATALINKFRAME_SIZE1_4  4
#define DNPBNCFG_MAXNUMOCTETSRECEIVEDINDATALINKFRAME_SIZE1_4  4

/*field size definitions for section 1.5 of the binary configuration file */
#define DNPBNCFG_CONTROL_SIZE1_5                        4
#define DNPBNCFG_SPECIALCONTROL_SIZE1_5                 4
#define DNPBNCFG_MAXTRANSMITTEDFRAGMENTSIZE_SIZE1_5     4
#define DNPBNCFG_MAXFILETRANSFERTRANSMITTEDFRAGMENTSIZE_SIZE1_5     4
#define DNPBNCFG_MAXRECEIVEDFRAGMENTSIZE_SIZE1_5        4
#define DNPBNCFG_MAXOBJECTSINCROBCONTROLREQUEST_SIZE1_5 4
#define DNPBNCFG_MAXOBJECTSINANALOGOUTPUTCONTROLREQUEST_SIZE1_5     4
#define DNPBNCFG_MAXOBJECTSINDATASETSCONTROLREQUEST_SIZE1_5         4
#define DNPBNCFG_SUPPORTSMIXEDOBJECTGROUPSINCONTROLREQUEST_SIZE1_5  4

/*field size definitions for section 1.6 of the binary configuration file */
#define DNPBNCFG_CONTROL_SIZE1_6          4
#define DNPBNCFG_SPECIALCONTROL_SIZE1_6   4
#define DNPBNCFG_APPLLAYERCOMPLETERESPONSETIMEOUT_SIZE1_6   4
#define DNPBNCFG_APPLLAYERFRAGMENTRESPONSETIMEOUT_SIZE1_6   4

/*field size definitions for section 1.7 of the binary configuration file */
#define DNPBNCFG_CONTROL_SIZE1_7                            4
#define DNPBNCFG_SPECIALCONTROL_SIZE1_7                     4
#define DNPBNCFG_APPLICATIONLAYERCONFIRMTIMEOUT_SIZE1_7     4
#define DNPBNCFG_TIMESYNCREQUIRED_SIZE1_7                   4
#define DNPBNCFG_FILEHANDLETIMEOUT_SIZE1_7                  4
#define DNPBNCFG_EVENTBUFFEROVERFLOWBEHAVIOR_SIZE1_7        4

/*field size definitions for section 1.8 of the binary configuration file */
#define DNPBNCFG_CONTROL_SIZE1_8                  4
#define DNPBNCFG_SPECIALCONTROL_SIZE1_8           4
#define DNPBNCFG_MASTERDATALINKADDRESS_SIZE1_8    4
#define DNPBNCFG_UNSOLICITEDRESPONSECONFIRMATIONTIMEOUT_SIZE1_8   4
#define DNPBNCFG_MAXUNSOLICITEDRETRIES_SIZE1_8    4

/*field size definitions for section 1.9 of the binary configuration file */
#define DNPBNCFG_CONTROL_SIZE1_9                        4
#define DNPBNCFG_SPECIALCONTROL_SIZE1_9                 4
#define DNPBNCFG_NUMBEROFCLASSONEEVENTS_SIZE1_9         4
#define DNPBNCFG_NUMBEROFCLASSTWOEVENTS_SIZE1_9         4
#define DNPBNCFG_NUMBEROFCLASSTHREEEVENTS_SIZE1_9       4
#define DNPBNCFG_HOLDTIMEAFTERCLASSONEEVENT_SIZE1_9     4
#define DNPBNCFG_HOLDTIMEAFTERCLASSTWOEVENT_SIZE1_9     4
#define DNPBNCFG_HOLDTIMEAFTERCLASSTHREEEVENT_SIZE1_9   4

/*field size definitions for section 1.10 of the binary configuration file */
#define DNPBNCFG_CONTROL_SIZE1_10                       4
#define DNPBNCFG_SPECIALCONTROL_SIZE1_10                4
#define DNPBNCFG_OUTSTATIONSETSIIN14_SIZE1_10           4
#define DNPBNCFG_AFTERLASTTIMESYNCOUTSTATIONSETSIIN14_SIZE1_10      4
#define DNPBNCFG_WHENTIMEERROREXCEEDSOUTSTATIONSETSIIN14_SIZE1_10   4

/*field size definitions for section 1.11 of the binary configuration file */
#define DNPBNCFG_CONTROL_SIZE1_11               4
#define DNPBNCFG_OUTSTATIONLOCATION_SIZE1_11    64
#define DNPBNCFG_OUTSTATIONID_SIZE1_11          64
#define DNPBNCFG_OUTSTATIONNAME_SIZE1_11        64

/*field size definitions for section 1.12 of the binary configuration file */
#define DNPBNCFG_CONTROL_SIZE1_12                         4
#define DNPBNCFG_SPECIALCONTROL_SIZE1_12                  4
#define DNPBNCFG_VERSIONOFSECUREAUTHENTICATIONSUPPORTED_SIZE1_12    4
#define DNPBNCFG_MAXNUMBERUSERS_SIZE1_12                  4
#define DNPBNCFG_SECURITYRESPONSETIMEOUT_SIZE1_12         4
#define DNPBNCFG_SESSIONKEYCHANGEINTERVAL_SIZE1_12        4
#define DNPBNCFG_SESSIONKEYCHANGEMESSAGECOUNT_SIZE1_12    4
#define DNPBNCFG_MAXERRORCOUNT_SIZE1_12                   4
#define DNPBNCFG_HMACALGORITHMREQUESTED_SIZE1_12          4
#define DNPBNCFG_KEYWRAPALGORITHM_SIZE1_12                4
#define DNPBNCFG_ADDITIONALCRITICALFCS_SIZE1_12           4
#define DNPBNCFG_REMOTEKEYUPDATECHANGE_SIZE1_12           4

/*field size definitions for section 1.13 of the binary configuration file */
#define DNPBNCFG_CONTROL_SIZE1_13             4
#define DNPBNCFG_SPECIALCONTROL_SIZE1_13      4

/*field size definitions for the header of the binary configuration file */
#define DNPBNCFG_BIN_CONFIG_HEADER_FIELD_LEN  8

/*values used to read section 1.1 of a binary configuration file. */
/*control bits to determine fields used in the file */
#define CRTL_DEVFUNCT1_1_1      1UL
#define CRTL_VENDNAME1_1_2      2UL
#define CRTL_DEVNAME1_1_3       4UL
#define CRTL_HARDVER1_1_4       8UL
#define CRTL_SOFTVER1_1_5       16UL
#define CRTL_DOCVERNUM1_1_6     32UL
#define CRTL_DNPLEVELS1_1_7     64UL
#define CRTL_FUNCBLOCKS1_1_8    128UL
#define CRTL_METHTOSETPAR1_1_10 512UL
#define CRTL_CONNECTIONSUP1_1_13 4096UL

#define FUNCTION_MASTER1_1      1UL
#define FUNCTION_OUTSTATION1_1  2UL

/*DNP levels */
#define DNPLEVELS_REQUESTSNONE      1UL
#define DNPLEVELS_REQUESTSLEVEL1    2UL
#define DNPLEVELS_REQUESTSLEVEL2    4UL
#define DNPLEVELS_REQUESTSLEVEL3    8UL
#define DNPLEVELS_REQUESTSLEVEL4    16UL
#define DNPLEVELS_RESPONSESNONE     256UL
#define DNPLEVELS_RESPONSESLEVEL1   512UL
#define DNPLEVELS_RESPONSESLEVEL2   1024UL
#define DNPLEVELS_RESPONSESLEVEL3   2048UL
#define DNPLEVELS_RESPONSESLEVEL4   4096UL
#define DNPLEVELS_BOTHNONE          257UL
#define DNPLEVELS_BOTHLEVEL1        514UL
#define DNPLEVELS_BOTHLEVEL2        1028UL
#define DNPLEVELS_BOTHLEVEL3        2056UL
#define DNPLEVELS_BOTHLEVEL4        4112UL

/*supported function blocks */
#define SUPPORTEDFB_SELFADDRESSRESERVATION  1UL
#define SUPPORTEDFB_DATASETS                2UL
#define SUPPORTEDFB_FILETRANSFER            4UL
#define SUPPORTEDFB_VIRTUALTERMINAL         8UL
#define SUPPORTEDFB_MAPPINGTOIEC61850OBJECTMODELS   16UL
#define SUPPORTEDFB_FC31ACTIVATECONFIGURATION       32UL
#define SUPPORTEDFB_SECUREAUTHENTICATION    64UL

/*methods to set configuration */
#define METHODS_XMLLOADEDVIADNPFILETRANSFER           1UL
#define METHODS_XMLLOADEDVIAOTHERTRANPORTMECH         2UL
#define METHODS_TERMINALASCIITERMINALCOMMANDLINE      4UL
#define METHODS_PROPRIETARYLOADEDVIADNPFILETRANSER    8UL
#define METHODS_PROPRIETARYLOADEDVIAOTHERTRANPORTMECH 16UL
#define METHODS_DIRECTKEYPADONDEVICEFRONTEND          32UL
#define METHODS_FACTORYSPECIFIEDWHENDEVICEISORDERED   64UL
#define METHODS_PROTOCOLSETVIADNP3                    128UL

/*connection types */
#define CONNTYPES_SERIAL1_1   1
#define CONNTYPES_NETWORK1_1  2

/*values used to read section 1.2 of a binary configuration file. */
/*control bits to determine fields used in the file */
#define CRTL_PORTNAME1_2_1                  1UL
#define CRTL_BAUDRATE1_2_3                  4UL
#define CRTL_FLOWCRTL1_2_4                  8UL
#define CRTL_LINKSTATUSINT1_2_5             16UL
#define CRTL_SUPPORTSDNP3COLLAVOID1_2_6     32UL
#define CRTL_RECEIVERINTERCHARTIMEOUT1_2_7  64UL
#define CRTL_INTERCHARGAPSINTX1_2_8         128UL

/*control bits to determine special values of fields */
#define SPCTRL_NONEFLOWCRTL1_2_4                            8UL
#define SPCTRL_NOTSUPPORTEDLINKSTATUSINT1_2_5               16UL
#define SPCTRL_NOSUPPORTFORDNP3COLLAVOID1_2_6               32UL
#define SPCTRL_NOTCHECKEDRECEIVERINTERCHARTIMEOUT1_2_7      64UL
#define SPCTRL_NOGAPPERMITTEDRECEIVERINTERCHARTIMEOUT1_2_7  128UL
#define SPCTRL_USEBITTIMEFORRECEIVERINTERCHARTIMEOUT1_2_7   256UL
#define SPCTRL_VARIABLERRECEIVERINTERCHARTIMEOUT1_2_7       512UL
#define SPCTRL_NONEINTERCHARGAPSINTX1_2_8                   1024UL
#define SPCTRL_USEBITTIMEFORINTERCHARGAPSINTX1_2_8          2048UL

/*Flow Control Settings */
#define FLOWCONTROLSETTINGS_ASSERTSRTSBEFORETX             0x00000001UL
#define FLOWCONTROLSETTINGS_ASSERTSDTRBEFORETX             0x00000002UL
#define FLOWCONTROLSETTINGS_ASSERTSRTSBEFORERX             0x00000004UL
#define FLOWCONTROLSETTINGS_ASSERTSDTRBEFORERX             0x00000008UL
#define FLOWCONTROLSETTINGS_ASSERTSALWAYSRTS               0x00000010UL
#define FLOWCONTROLSETTINGS_ASSERTSALWAYSDTR               0x00000020UL
#define FLOWCONTROLSETTINGS_REQBEFORETXCTSASSERTED         0x00000040UL
#define FLOWCONTROLSETTINGS_REQBEFORETXCTSDEASSERTED       0x00000080UL
#define FLOWCONTROLSETTINGS_REQBEFORETXDCDASSERTED         0x00000010UL
#define FLOWCONTROLSETTINGS_REQBEFORETXDCDDEASSERTED       0x00000020UL
#define FLOWCONTROLSETTINGS_REQBEFORETXDSRASSERTED         0x00000040UL
#define FLOWCONTROLSETTINGS_REQBEFORETXDSRDEASSERTED       0x00000080UL
#define FLOWCONTROLSETTINGS_REQBEFORETXRIASSERTED          0x00000100UL
#define FLOWCONTROLSETTINGS_REQBEFORETXRIDEASSERTED        0x00000200UL
#define FLOWCONTROLSETTINGS_REQRXINACTIVEBEFORETX          0x00000400UL
#define FLOWCONTROLSETTINGS_REQBEFORERXCTSASSERTED         0x00000800UL
#define FLOWCONTROLSETTINGS_REQBEFORERXCTSDEASSERTED       0x00001000UL
#define FLOWCONTROLSETTINGS_REQBEFORERXDCDASSERTED         0x00002000UL
#define FLOWCONTROLSETTINGS_REQBEFORERXDCDDEASSERTED       0x00004000UL
#define FLOWCONTROLSETTINGS_REQBEFORERXDSRASSERTED         0x00008000UL
#define FLOWCONTROLSETTINGS_REQBEFORERXDSRDEASSERTED       0x00010000UL
#define FLOWCONTROLSETTINGS_REQBEFORERXRIASSERTED          0x00020000UL
#define FLOWCONTROLSETTINGS_REQBEFORERXRIDEASSERTED        0x00040000UL
#define FLOWCONTROLSETTINGS_ALWAYSIGNORESCTS               0x00080000UL
#define FLOWCONTROLSETTINGS_ALWAYSIGNORESDCD               0x00100000UL
#define FLOWCONTROLSETTINGS_ALWAYSIGNORESDSR               0x00200000UL
#define FLOWCONTROLSETTINGS_ALWAYSIGNORESRI                0x00400000UL
#define FLOWCONTROLSETTINGS_REQINDICATIONBEFORERXRS422     0x00800000UL
#define FLOWCONTROLSETTINGS_ASSERTSCONTROLBEFORETXRS422    0x01000000UL
#define FLOWCONTROLSETTINGS_REQRXINACTIVEBEFORETXRS485     0x02000000UL


/*values used to read section 1.3 of a binary configuration file. */
/*control bits to determine fields used in the file */
#define CRTL_PORTNAME1_3_1                           1UL
#define CRTL_TYPEOFENDPOINT1_3_2                     2UL
#define CRTL_IPOFDEVICE1_3_3                         4UL
#define CRTL_SUBNETMASK1_3_4                         8UL
#define CRTL_GATEWAYIPADDR1_3_5                      16UL
#define CRTL_ACCEPTSTCPCONNSORUDPDARAGRAMS1_3_6      32UL
#define CRTL_IPADDRSTOACCEPTTCPANDUDP1_3_7           64UL
#define CRTL_TCPLISTENPORTNUMBER1_3_8                128UL
#define CRTL_TCPLISTENPORTNUMBEROFREMOTE1_3_9        256UL
#define CRTL_TCPKEEPALIVETIMER1_3_10                 512UL
#define CRTL_LOCALUDPPORT1_3_11                      1024UL
#define CRTL_DESINTATIONUDPPORTFORDNP3REQ1_3_12      2048UL
#define CRTL_DESINTATIONUDPPORTFORINITIALUNSOLNULLRESP1_3_13   4096UL
#define CRTL_DESINTATIONUDPPORTFORRESPONSES1_3_14    8192UL
#define CRTL_MULTIPLEOUTSTATIONCONNECTIONS1_3_15     16384UL
#define CRTL_MULTIPLEMASTERCONNECTIONS1_3_16         32768UL
#define CRTL_TIMESYNCHSUPPORT1_3_17                  65536UL

/*control bits to determine special values of fields */
#define SPCTRL_NOTAPPLICABLETCPLISTENPORT1_3_8                      1UL
#define SPCTRL_NOTAPPLICABLETCPLISTENPORTOFREMOTE1_3_9              2UL
#define SPCTRL_LETSYSTEMCHOOSELOCALUDPPORT1_3_11                    4UL
#define SPCTRL_NONEDESINTATIONUDPPORTFORINITIALUNSOLNULLRESP1_3_13  8UL
#define SPCTRL_NONEDESINTATIONUDPPORTFORRESPONSES1_3_14             16UL
#define SPCTRL_SUPPORTSMULTIPLEOUTSTATIONCONNECTIONS1_3_15          32UL
#define SPCTRL_SUPPORTSMULTIPLEMASTERCONNECTIONS1_3_16              64UL
#define SPCTRL_NOTSUPPORTEDTIMESYNCHRONIZATION1_3_17                128UL
#define SPCTRL_USESOURCEPORTNUMBERDESINTATIONUDPPORTFORRESP1_3_14   256UL

/*endpoint type */
#define ENDPOINTS_TCPINITIATING   1UL
#define ENDPOINTS_TCPLISTENING    2UL
#define ENDPOINTS_TCPDUAL         4UL
#define ENDPOINTS_UDPDATAGRAM     8UL

/*where to accept TCP or UDP from */
#define ACCEPTSTCPORUDP_ALLOWALL                1UL
#define ACCEPTSTCPORUDP_LIMITSBASEONIPADDRESS   2UL
#define ACCEPTSTCPORUDP_LIMITSBASEONLISTOFIPADDRESSES   4UL
#define ACCEPTSTCPORUDP_LIMITSBASEONWILDCARDIPADDRESS   8UL
#define ACCEPTSTCPORUDP_LIMITSBASEONLISTOFWILDCARDADDRESSES   16UL

/*multiple master methods */
#define MULTMASTERMETHOD_BASEDONIPADDRESS         1UL
#define MULTMASTERMETHOD_BASEDONIPPORTNUMBER      2UL
#define MULTMASTERMETHOD_BROWSINGFORSTATICDATA    4UL

/*time synch support */
#define TIMESYNCHSUPPORT_DNP3LANPROCEDURE     1UL
#define TIMESYNCHSUPPORT_DNP3WRITETIME        2UL

/*values used to read section 1.4 of a binary configuration file. */
/*control bits to determine fields used in the file */
#define CRTL_DATALINKADDRESS1_4_1                      1UL
#define CRTL_DNP3SOURCEADDRVALIDATION1_4_2             2UL
#define CRTL_SOURCEADDRSEXPECTEDWITHVAL1_4_3           4UL
#define CRTL_SELFADDRUSINGFFFC1_4_4                    8UL
#define CRTL_SENDSCONFIRMEDUSERDATAFRAMES1_4_5         16UL
#define CRTL_DATALINKLAYERCONFIRMTIMEOUT1_4_6          32UL
#define CRTL_MAXDATALINKRETRIES1_4_7                   64UL
#define CRTL_MAXNUMOCTETSTXINDATALINKFRAME1_4_8        128UL
#define CRTL_MAXNUMOCTETSRECEIVEDINDATALINKFRAME1_4_9  256UL

/*control bits to determine special values of fields */
#define SPCTRL_ANY16BITDATALINKADDRESS1_4_3             1UL
#define SPCTRL_SUPPORTSSELFADDRUSINGFFFC1_4_4           2UL
#define SPCTRL_NONEDATALINKLAYERCONFTIMEOUT1_4_6        4UL
#define SPCTRL_VARIABLEDATALINKLAYERCONFTIMEOUT1_4_6    8UL
#define SPCTRL_NEVERRETRIESMAXDATALINKRETRIES1_4_7      16UL

/*source address validation */
#define SOURCEADDRVAL_NEVER                 1UL
#define SOURCEADDRVAL_ALWAYSSINGLEADDR      2UL
#define SOURCEADDRVAL_ALWAYSMULTIPLEADDRS   4UL
#define SOURCEADDRVAL_SOMETIMES             8UL

/*sends confirmed user data frames */
#define SENDSCONFFRAMES_NEVER     1UL
#define SENDSCONFFRAMES_SOMETIMES 2UL
#define SENDSCONFFRAMES_ALWAYS    4UL

/*values used to read section 1.5 of a binary configuration file. */
/*control bits to determine fields used in the file */
#define CRTL_MAXTRANSMITTEDFRAGMENTSIZE1_5_1                    1UL
#define CRTL_MAXFILETRANSFERTRANSMITTEDFRAGMENTSIZE1_5_2        2UL
#define CRTL_MAXRECEIVEDFRAGMENTSIZE1_5_3                       4UL
#define CRTL_MAXOBJECTSINCROBCONTROLREQUEST1_5_5                16UL
#define CRTL_MAXOBJECTSINANALOGOUTPUTCONTROLREQUEST1_5_6        32UL
#define CRTL_MAXOBJECTSINDATASETSCONTROLREQUEST1_5_7            64UL
#define CRTL_SUPPORTSMIXEDOBJECTGROUPSINCONTROLREQUEST1_5_8     128UL

/*control bits to determine special values of fields */
#define SPCTRL_VARIABLEMAXOBJECTSINCROBCONTROLREQUEST1_5_5            1UL
#define SPCTRL_VARIABLEMAXOBJECTSINANALOGOUTPUTCONTROLREQUEST1_5_6    2UL
#define SPCTRL_VARIABLEMAXOBJECTSINDATASETSCONTROLREQUEST1_5_7        4UL
#define SPCTRL_DOESSUPPORTMIXEDOBJECTGROUPSINCONTROLREQUEST1_5_8      8UL

/*values used to read section 1.6 of a binary configuration file. */
/*control bits to determine fields used in the file */
#define CRTL_APPLLAYERCOMPLETERESPONSETIMEOUT1_6_1    1UL
#define CRTL_APPLLAYERFRAGMENTRESPONSETIMEOUT1_6_3    4UL

/*control bits to determine special values of fields */
#define SPCTRL_NONEAPPLLAYERCOMPLETERESPONSETIMEOUT1_6_1        1UL
#define SPCTRL_VARIABLEAPPLLAYERCOMPLETERESPONSETIMEOUT1_6_1    2UL
#define SPCTRL_NONEAPPLLAYERFRAGMENTRESPONSETIMEOUT1_6_3        4UL
#define SPCTRL_VARIABLEAPPLLAYERFRAGMENTRESPONSETIMEOUT1_6_3    8UL

/*values used to read section 1.7 of a binary configuration file. */
/*control bits to determine fields used in the file */
#define CRTL_APPLICATIONLAYERCONFIRMTIMEOUT1_7_1    1UL
#define CRTL_TIMESYNCREQUIRED1_7_2                  2UL
#define CRTL_FILEHANDLETIMEOUT1_7_4                 8UL
#define CRTL_EVENTBUFFEROVERFLOWBEHAVIOR1_7_5       16UL
#define CRTL_SENDSMULTIFRAGMENTRESPONSES1_7_7       64UL
#define CRTL_REQUESTSAPPLICATIONCONFIRMATION1_7_11  2048UL


/*control bits to determine special values of fields */
#define SPCTRL_NONEAPPLICATIONLAYERCONFIRMTIMEOUT1_7_1        1UL
#define SPCTRL_VARIABLEAPPLICATIONLAYERCONFIRMTIMEOUT1_7_1    2UL
#define SPCTRL_NOTAPPLICABLEFILEHANDLETIMEOUT1_7_4            4UL
#define SPCTRL_VARIABLEFILEHANDLETIMEOUT1_7_4                 8UL
#define SPCTRL_YESSENDSMULTIFRAGMENTRESPONSES1_7_7            16UL
#define SPCTRL_YESEVENTRESPONSES1_7_11                        32UL
#define SPCTRL_YESNONFINALFRAGMENTS1_7_11                     64UL

/*time sync required options */
#define TIMESYNCREQUIREDOPTIONS_NEVER                   1UL
#define TIMESYNCREQUIREDOPTIONS_WITHINSECONDSOFIIN14    2UL
#define TIMESYNCREQUIREDOPTIONS_PERIODICALLY            4UL

/*event buffer overflow behavior options */
#define EVENTBUFFEROVERFLOWBEHAVIOROPTIONS_DISCARDOLDEST    1UL
#define EVENTBUFFEROVERFLOWBEHAVIOROPTIONS_DISCARDNEWEST    2UL
#define EVENTBUFFEROVERFLOWBEHAVIOROPTIONS_OTHER            4UL

/*values used to read section 1.8 of a binary configuration file. */
/*control bits to determine fields used in the file */
#define CRTL_SUPPORTSUNSOLICITEDREPORTING1_8_1              1UL
#define CRTL_MASTERDATALINKADDRESS1_8_2                     2UL
#define CRTL_UNSOLICITEDRESPONSECONFIRMATIONTIMEOUT1_8_3    4UL
#define CRTL_MAXUNSOLICITEDRETRIES1_8_4                     8UL

/*control bits to determine special values of fields */
#define SPCTRL_ONSUPPORTSUNSOLICITEDREPORTING1_8_1          1UL
#define SPCTRL_VARIABLEUNSOLRESPONSECONFIRMTIMEOUT1_8_3     2UL
#define SPCTRL_NONEMAXUNSOLICITEDRETRIES1_8_4               4UL
#define SPCTRL_INFINITEMAXUNSOLICITEDRETRIES1_8_4           8UL

/*values used to read section 1.9 of a binary configuration file. */
/*control bits to determine fields used in the file */
#define CRTL_NUMBEROFCLASSONEEVENTS1_9_1          1UL
#define CRTL_NUMBEROFCLASSTWOEVENTS1_9_2          2UL
#define CRTL_NUMBEROFCLASSTHREEEVENTS1_9_3        4UL
#define CRTL_HOLDTIMEAFTERCLASSONEEVENT1_9_5      8UL
#define CRTL_HOLDTIMEAFTERCLASSTWOEVENT1_9_6      16UL
#define CRTL_HOLDTIMEAFTERCLASSTHREEEVENT1_9_7    32UL

/*control bits to determine special values of fields */
#define SPCTRL_CLASSONENOTUSEDTOTRIGGERUNSOLRESPS1_9_1_AND_1_9_5    1UL
#define SPCTRL_CLASSTWONOTUSEDTOTRIGGERUNSOLRESPS1_9_2_AND_1_9_6    2UL
#define SPCTRL_CLASSTHREENOTUSEDTOTRIGGERUNSOLRESPS1_9_3_AND_1_9_7  4UL

/*values used to read section 1.10 of a binary configuration file. */
/*control bits to determine fields used in the file */
#define CRTL_OUTSTATIONSETSIIN14_1_10_2     1UL

/*control bits to determine special values of fields */
#define SPCTRL_NEVEROUTSTATIONSETSIIN1_10_2                   1UL
#define SPCTRL_ATSTARTUPOUTSTATIONSETSIIN1_10_2               2UL
#define SPCTRL_PERIODICALLYOUTSTATIONSETSIIN1_10_2            4UL
#define SPCTRL_AFTERLASTTIMESYNCOUTSTATIONSETSIIN1_10_2       8UL
#define SPCTRL_WHENTIMEERROREXCEEDSOUTSTATIONSETSIIN1_10_2    16UL

/*values used to read section 1.11 of a binary configuration file. */
/*control bits to determine fields used in the file */
#define CRTL_OUTSTATIONLOCATION1_11_1   1UL
#define CRTL_OUTSTATIONID1_11_2         2UL
#define CRTL_OUTSTATIONNAME1_11_3       4UL

/*values used to read section 1.12 of a binary configuration file. */
/*control bits to determine fields used in the file */
#define CRTL_SECUREAUTHENTICATIONSUPPORTED1_12_1   1UL
#define CRTL_MAXNUMBERUSERS1_12_2                  2UL
#define CRTL_SECURITYRESPONSETIMEOUT1_12_3         4UL
#define CRTL_ACCEPTSAGGRESSIVEMODE1_12_4           8UL
#define CRTL_SESSIONKEYCHANGEINTERVAL1_12_6        16UL
#define CRTL_SESSIONKEYCHANGEMESSAGECOUNT1_12_7    32UL
#define CRTL_MAXERRORCOUNT1_12_8                   64UL
#define CRTL_HMACALGORITHMREQUESTED1_12_9          128UL
#define CRTL_KEYWRAPALGORITHM1_12_10               256UL
#define CRTL_ADDITIONALCRITICALFCS1_12_15          8192UL
#define CRTL_REMOTEUPDATEKEYCHANGE1_12_17          32768UL

/*control bits to determine special values of fields */
#define SPCTRL_NOSECUREAUTHENTICATIONSUPPORT1_12_1         1UL
#define SPCTRL_YESACCEPTSAGGRESSIVEMODE1_12_4              2UL
#define SPCTRL_DISABLEDSESSIONKEYCHANGEINTERVAL1_12_6      4UL
#define SPCTRL_SUPPORTSKEYCHANGEBYSYMMETRICCRYPTO1_12_17   8UL
#define SPCTRL_SUPPORTSKEYCHANGEBYASYMMETRICCRYPTO1_12_17  16UL

/*MAC Algorithms */
#define MACALGORITHMS_SHA1TRUNCATED4      1UL
#define MACALGORITHMS_SHA1TRUNCATED8      2UL
#define MACALGORITHMS_SHA1TRUNCATED10     4UL
#define MACALGORITHMS_SHA256TRUNCATED8    8UL
#define MACALGORITHMS_SHA256TRUNCATED16   16UL
#define MACALGORITHMS_AESGMAC             32UL
#define MACALGORITHMS_OTHER               64UL

/*KeyWrap Algorithms */
#define KEYWRAPALGORITHMS_AES128          1UL
#define KEYWRAPALGORITHMS_AES256          2UL
#define KEYWRAPALGORITHMS_RSAESOAEP1024   4UL
#define KEYWRAPALGORITHMS_RSAESOAEP2048   8UL
#define KEYWRAPALGORITHMS_RSAESOAEP3072   16UL
#define KEYWRAPALGORITHMS_OTHER           32UL

/*Critical Function Codes */
#define CRITICALFUNCTIONCODES_FC0     1UL
#define CRITICALFUNCTIONCODES_FC1     2UL
#define CRITICALFUNCTIONCODES_FC7     4UL
#define CRITICALFUNCTIONCODES_FC8     8UL
#define CRITICALFUNCTIONCODES_FC9     16UL
#define CRITICALFUNCTIONCODES_FC10    32UL
#define CRITICALFUNCTIONCODES_FC11    64UL
#define CRITICALFUNCTIONCODES_FC12    128UL
#define CRITICALFUNCTIONCODES_FC22    256UL
#define CRITICALFUNCTIONCODES_FC23    512UL
#define CRITICALFUNCTIONCODES_FC25    1024UL
#define CRITICALFUNCTIONCODES_FC26    2048UL
#define CRITICALFUNCTIONCODES_FC27    4096UL
#define CRITICALFUNCTIONCODES_FC28    8192UL
#define CRITICALFUNCTIONCODES_FC30    16384UL
#define CRITICALFUNCTIONCODES_FC129   32768UL
#define CRITICALFUNCTIONCODES_FC130   65536UL

/*values used to read section 1.13 of a binary configuration file. */
/*control bits to determine fields used in the file */
#define CRTL_BROADCASTFUNCTIONALITYSUPPORTED        0x00000001UL
#define CRTL_BROADCASTFUNCTIONALITYFC2SUPPORTED     0x00000002UL
#define CRTL_BROADCASTFUNCTIONALITYFC5SUPPORTED     0x00000004UL
#define CRTL_BROADCASTFUNCTIONALITYFC6SUPPORTED     0x00000008UL
#define CRTL_BROADCASTFUNCTIONALITYFC7SUPPORTED     0x00000010UL
#define CRTL_BROADCASTFUNCTIONALITYFC8SUPPORTED     0x00000020UL
#define CRTL_BROADCASTFUNCTIONALITYFC9SUPPORTED     0x00000040UL
#define CRTL_BROADCASTFUNCTIONALITYFC10SUPPORTED    0x00000080UL
#define CRTL_BROADCASTFUNCTIONALITYFC11SUPPORTED    0x00000100UL
#define CRTL_BROADCASTFUNCTIONALITYFC12SUPPORTED    0x00000200UL
#define CRTL_BROADCASTFUNCTIONALITYFC13SUPPORTED    0x00000400UL
#define CRTL_BROADCASTFUNCTIONALITYFC14SUPPORTED    0x00000800UL
#define CRTL_BROADCASTFUNCTIONALITYFC15SUPPORTED    0x00001000UL
#define CRTL_BROADCASTFUNCTIONALITYFC16SUPPORTED    0x00002000UL
#define CRTL_BROADCASTFUNCTIONALITYFC17SUPPORTED    0x00004000UL
#define CRTL_BROADCASTFUNCTIONALITYFC18SUPPORTED    0x00008000UL
#define CRTL_BROADCASTFUNCTIONALITYFC19SUPPORTED    0x00010000UL
#define CRTL_BROADCASTFUNCTIONALITYFC20SUPPORTED    0x00020000UL
#define CRTL_BROADCASTFUNCTIONALITYFC21SUPPORTED    0x00040000UL
#define CRTL_BROADCASTFUNCTIONALITYFC22SUPPORTED    0x00080000UL
#define CRTL_BROADCASTFUNCTIONALITYFC24SUPPORTED    0x00100000UL
#define CRTL_BROADCASTFUNCTIONALITYFC31SUPPORTED    0x00200000UL

/*control bits to determine special values of fields */
#define SPCRTL_ENABLEDBROADCASTFUNCT                        0x00000001UL
#define SPCRTL_ENABLEDBROADCASTFUNCTFC2WRITECLOCK           0x00000002UL
#define SPCRTL_ENABLEDBROADCASTFUNCTFC2WRITELASTRECTIME     0x00000004UL
#define SPCRTL_ENABLEDBROADCASTFUNCTFC2CLEARRESTART         0x00000008UL
#define SPCRTL_ENABLEDBROADCASTFUNCTFC2WRITEOTHER           0x00000010UL
#define SPCRTL_ENABLEDBROADCASTFUNCTFC5     0x00000020UL
#define SPCRTL_ENABLEDBROADCASTFUNCTFC6     0x00000040UL
#define SPCRTL_ENABLEDBROADCASTFUNCTFC7     0x00000080UL
#define SPCRTL_ENABLEDBROADCASTFUNCTFC8     0x00000100UL
#define SPCRTL_ENABLEDBROADCASTFUNCTFC9     0x00000200UL
#define SPCRTL_ENABLEDBROADCASTFUNCTFC10    0x00000400UL
#define SPCRTL_ENABLEDBROADCASTFUNCTFC11    0x00000800UL
#define SPCRTL_ENABLEDBROADCASTFUNCTFC12    0x00001000UL
#define SPCRTL_ENABLEDBROADCASTFUNCTFC13    0x00002000UL
#define SPCRTL_ENABLEDBROADCASTFUNCTFC14    0x00004000UL
#define SPCRTL_ENABLEDBROADCASTFUNCTFC15    0x00008000UL
#define SPCRTL_ENABLEDBROADCASTFUNCTFC16    0x00010000UL
#define SPCRTL_ENABLEDBROADCASTFUNCTFC17    0x00020000UL
#define SPCRTL_ENABLEDBROADCASTFUNCTFC18    0x00040000UL
#define SPCRTL_ENABLEDBROADCASTFUNCTFC19    0x00080000UL
#define SPCRTL_ENABLEDBROADCASTFUNCTFC20ENABLEUNSOLBYEVENTCLASS     0x00100000UL
#define SPCRTL_ENABLEDBROADCASTFUNCTFC20ENABLEUNSOLOTHER            0x00200000UL
#define SPCRTL_ENABLEDBROADCASTFUNCTFC21DISABLEUNSOLBYEVENTCLASS    0x00400000UL
#define SPCRTL_ENABLEDBROADCASTFUNCTFC21DISABLEENABLEUNSOLOTHER     0x00800000UL
#define SPCRTL_ENABLEDBROADCASTFUNCTFC22    0x01000000UL
#define SPCRTL_ENABLEDBROADCASTFUNCTFC24    0x02000000UL
#define SPCRTL_ENABLEDBROADCASTFUNCTFC31    0x04000000UL

typedef struct DnpBinConfigFileValues {
  TMWTYPES_BOOL isOutStation;
  TMWTYPES_UCHAR xmlVersion[DNPBNCFG_BIN_CONFIG_HEADER_FIELD_LEN];
  TMWTYPES_UCHAR fileVersion[DNPBNCFG_BIN_CONFIG_HEADER_FIELD_LEN];
  
  /*Section 1.1 */
  TMWTYPES_ULONG fieldsUsed1_1;
  TMWTYPES_ULONG deviceFunction1_1;
  TMWTYPES_CHAR deviceName1_1[DNPBNCFG_DEVICENAME_SIZE1_1];
  TMWTYPES_ULONG connectionsSupported1_1;

  /*Section 1.2 */
  TMWTYPES_ULONG fieldsUsed1_2;
  TMWTYPES_ULONG specialControls1_2;
  TMWTYPES_CHAR portName1_2[DNPBNCFG_PORTNAME_SIZE1_2];
  TMWTYPES_ULONG baudRate1_2;
  TMWTYPES_ULONG flowControl1_2;
  TMWTYPES_ULONG linkStatusInterval1_2;
  TMWTYPES_ULONG minBackOffTimeCollAviod1_2;
  TMWTYPES_ULONG maxRandBackOffTimeCollAviod1_2;
  TMWTYPES_ULONG receiverInterCharTimeout1_2;
  TMWTYPES_ULONG interCharMaxGapsInTx1_2;

  /*Section 1.3 */
  TMWTYPES_ULONG fieldsUsed1_3;
  TMWTYPES_ULONG specialControls1_3;
  TMWTYPES_CHAR portName1_3[DNPBNCFG_PORTNAME_SIZE1_3];
  TMWTYPES_ULONG typeOfEndpoint1_3;
  TMWTYPES_CHAR ipOfDevice1_3[DNPBNCFG_IPOFDEVICE_SIZE1_3];
  TMWTYPES_CHAR subnetMask1_3[DNPBNCFG_SUBNETMASK_SIZE1_3];
  TMWTYPES_CHAR gatewayIpAddr1_3[DNPBNCFG_GATEWAYIPADDR_SIZE1_3];
  TMWTYPES_ULONG acceptsTcpConnsOrUdp1_3;
  TMWTYPES_ULONG ipAddrsToAcceptTcpandUdpCount1_3;
  TMWTYPES_CHAR ipAddrToAcceptTcpandUdp1_3[DNPBNCFG_MAXNUMIPADDRS1_3][DNPBNCFG_IPADDRTOACCEPTTCPANDUDP_SIZE1_3];
  TMWTYPES_ULONG tcpListenPortNumber1_3;
  TMWTYPES_ULONG tcpListenPortNumberOfRemote1_3;
  TMWTYPES_ULONG tcpKeepAliveTimer1_3;
  TMWTYPES_ULONG localUdpPort1_3;
  TMWTYPES_ULONG destUdpPortForDnp3req1_3;
  TMWTYPES_ULONG destUdpPortForInitialUnsolNullResp1_3;
  TMWTYPES_ULONG destUdpPortForResponses1_3;
  TMWTYPES_ULONG multiMasterConnections1_3;
  TMWTYPES_ULONG timeSynchSupport1_3;

  /*Section 1.4 */
  TMWTYPES_ULONG fieldsUsed1_4;
  TMWTYPES_ULONG specialControls1_4;
  TMWTYPES_ULONG dataLinkAddress1_4;
  TMWTYPES_ULONG dnp3SourceAddrValidation1_4;
  TMWTYPES_ULONG dnp3SourceAddrs1_4;
  TMWTYPES_ULONG sendsConfirmedUserDataFrames1_4;
  TMWTYPES_ULONG dataLinkLayerConfirmTimeout1_4;
  TMWTYPES_ULONG maxDataLinkRetries1_4;
  TMWTYPES_ULONG maxNumOctetsTxDataLinkFrame1_4;
  TMWTYPES_ULONG maxNumOctetsRxDataLinkFrame1_4;

  /*Section 1.5 */
  TMWTYPES_ULONG fieldsUsed1_5;
  TMWTYPES_ULONG specialControls1_5;
  TMWTYPES_ULONG maxTxFragmentSize1_5;
  TMWTYPES_ULONG maxFileTransferTxFragSize1_5;
  TMWTYPES_ULONG maxRxFragmentSize1_5;
  TMWTYPES_ULONG maxObjsInCROBControlRequest1_5;
  TMWTYPES_ULONG maxObjsInAnalogOutputCtrlReq1_5;
  TMWTYPES_ULONG maxObjsInDataSetsCtrlReq1_5;
  TMWTYPES_ULONG supportsMixedObjGrpsInCtrlReq1_5;

  /*Section 1.6 */
  TMWTYPES_ULONG fieldsUsed1_6;
  TMWTYPES_ULONG specialControls1_6;
  TMWTYPES_ULONG applLayerCompleteRespTimeout1_6;
  TMWTYPES_ULONG applLayerFragRespTimeout1_6;

  /*Section 1.7 */
  TMWTYPES_ULONG fieldsUsed1_7;
  TMWTYPES_ULONG specialControls1_7;
  TMWTYPES_ULONG applLayerConfirmTimeout1_7;
  TMWTYPES_ULONG timeSyncRequired1_7;
  TMWTYPES_ULONG fileHandleTimeout1_7;
  TMWTYPES_ULONG eventBufOverflowBehavior1_7;

  /*Section 1.8 */
  TMWTYPES_ULONG fieldsUsed1_8;
  TMWTYPES_ULONG specialControls1_8;
  TMWTYPES_ULONG masterDataLinkAddr1_8;
  TMWTYPES_ULONG unsolRespConfirmTimeout1_8;
  TMWTYPES_ULONG maxUnsolicitedRetries1_8;

  /*Section 1.9 */
  TMWTYPES_ULONG fieldsUsed1_9;
  TMWTYPES_ULONG specialControls1_9;
  TMWTYPES_ULONG numClassOneEvents1_9;
  TMWTYPES_ULONG numClassTwoEvents1_9;
  TMWTYPES_ULONG numClassThreeEvents1_9;
  TMWTYPES_ULONG holdTimeAfterClassOneEvent1_9;
  TMWTYPES_ULONG holdTimeAfterClassTwoEvent1_9;
  TMWTYPES_ULONG holdTimeAfterClassThreeEvent1_9;

  /*Section 1.10 */
  TMWTYPES_ULONG fieldsUsed1_10;
  TMWTYPES_ULONG specialControls1_10;
  TMWTYPES_ULONG outStationSetsIIN14_1_10;
  TMWTYPES_ULONG afterLastTimeSyncOutstationSetsIIN14_1_10;
  TMWTYPES_ULONG whenTimeErrExceedsOutstationSetsIIN14_1_10;

  /*Section 1.11 */
  TMWTYPES_ULONG fieldsUsed1_11;
  TMWTYPES_CHAR outstationLocation1_11[DNPBNCFG_OUTSTATIONLOCATION_SIZE1_11];
  TMWTYPES_CHAR outstationId1_11[DNPBNCFG_OUTSTATIONID_SIZE1_11];
  TMWTYPES_CHAR outstationName1_11[DNPBNCFG_OUTSTATIONNAME_SIZE1_11];

  /*Section 1.12 */
  TMWTYPES_ULONG fieldsUsed1_12;
  TMWTYPES_ULONG specialControls1_12;
  TMWTYPES_ULONG versionSecureAuthSupported1_12;
  TMWTYPES_ULONG maxNumberUsers1_12;
  TMWTYPES_ULONG securityResponseTimeout1_12;
  TMWTYPES_ULONG sessionKeyChangeInterval1_12;
  TMWTYPES_ULONG sessionKeyChangeMessageCnt1_12;
  TMWTYPES_ULONG maxErrorCount1_12;
  TMWTYPES_ULONG hmacAlgorithmRequested1_12;
  TMWTYPES_ULONG keyWrapAlgorithm1_12;
  TMWTYPES_ULONG additionalCriticalFcs1_12;
  TMWTYPES_ULONG remoteKeyUpdateChange1_12;

  /*Section 1.13 */
  TMWTYPES_ULONG fieldsUsed1_13;
  TMWTYPES_ULONG specialControls1_13;
  
} DNPBNCFG_FILEVALUES;


#ifdef __cplusplus
extern "C" {
#endif

#if DNPCNFG_SUPPORT_BINCONFIG
TMWDEFS_SCL_API TMWTYPES_BOOL TMWDEFS_GLOBAL dnpbncfg_ReadBinaryConfigFile(
  FILE *fp, 
  DNPBNCFG_FILEVALUES *pBinFileValues,
  TMWTARG_BINFILE_VALS *pTargBinFileValues,
  TMWTYPES_USHORT *pXMLVersion);

#endif

#ifdef __cplusplus
}
#endif
#endif
